content:
  - name: opl-docs
    label: "OPL Documentation"
    type: collection
    path: documentation/OPL-docs
    filename: "v{fields.version}.md"
    format: yaml-frontmatter
    fields:
      - name: version
        label: "Version"
        type: string
      - name: title
        label: "Title"
        type: string
      - name: logo
        label: "Logo"
        type: media
      - name: summary
        label: "Summary"
        type: text
      - name: body
        label: "Content"
        type: rich-text